services:
  webui:
    build: .
    container_name: "moneyprinterturbo-webui"
    ports:
      - "8501:8501"
    volumes:
      # 仅挂载需要持久化的目录，不再挂载config.toml
      - ./storage:/MoneyPrinterTurbo/storage
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
